# Generated by Django 5.2 on 2025-05-23 14:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_reaction_created_at'),
        ('notifications', '0002_notification_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='reaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.reaction'),
        ),
    ]
